from typing import Any, Optional

class StacrsError(Exception): ...

def main() -> int: ...
def migrate_href(href: str, version: Optional[str] = None) -> dict[str, Any]: ...
def migrate(value: dict[str, Any], version: Optional[str] = None) -> dict[str, Any]: ...
def validate_href(href: str) -> None: ...
def validate(value: dict[str, Any]) -> None: ...
