#!/usr/bin/env sh

set -e

rm -rf target/criterion
cargo criterion --color never --output-format bencher --history-id $(git describe)
cp -r target/criterion/reports benches

for file in $(find benches/reports -iname '*.svg'); do
    sed -i.bak 's/svg width/svg style="background-color: white;" width/' $file
    rm $file.bak
done
