#!/usr/bin/env sh

set -e

rm -rf target/criterion
branch=$(git describe --contains --all HEAD)
git checkout $(git describe --abbrev=0)
cargo criterion --history-id $(git describe)
git checkout $branch
cargo criterion --history-id $branch
