#!/usr/bin/env sh
#
# Validate stac server using stac-api-validator.
#
# To use this script on macos, you'll need `timeout`, which is provided by Homebrew's coreutils:
#
#   brew install coreutils

set -e

args="crates/server/data/sentinel-2/*"
build_args="--no-default-features"
conformance="--conformance core --conformance features --conformance item-search"

if [ $# -eq 1 ]; then
    if [ "$1" = "--pgstac" ]; then
        args="$args --pgstac postgres://username:password@localhost/postgis"
        build_args="$build_args -F pgstac"
        conformance="$conformance --conformance filter"
    else
        echo "Unknown argument: $1"
        exit 1
    fi
fi

cargo build -p rustac $build_args
cargo run -p rustac $build_args -- serve $args &
server_pid=$!
echo "server_pid=$server_pid"
set +e
scripts/wait-for-it.sh localhost:7822 && \
    stac-api-validator \
        --root-url http://localhost:7822 \
        $conformance \
        --collection sentinel-2-c1-l2a \
        --geometry '{"type":"Point","coordinates":[-105.07,40.08]}'
status=$?
set -e
kill $server_pid
exit $status
