name: CD

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-docs:
    name: Build docs
    runs-on: ubuntu-latest
    env:
      GIT_COMMITTER_NAME: ci-bot
      GIT_COMMITTER_EMAIL: ci-bot@example.com
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      - name: Sync
        run: uv sync --group docs
      - name: Build
        run: uv run mkdocs build
      - uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        id: deployment
        with:
          path: site/
  deploy-docs:
    needs: build-docs
    name: Deploy docs
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346 # v5.0.1
        id: deployment
  coverage:
    name: Coverage
    environment: codecov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: Swatinem/rust-cache@f0d9c3887740aee45f6153b24b3a6b815192ec16 # v2
      - name: Install tarpaulin
        run: cargo install cargo-tarpaulin
      - name: Test w/ coverage
        run: cargo tarpaulin -p stac --all-features --out xml
      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          files: ./cobertura.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
